### ISSUE TITLE
TM1637Display.h is a blocking library

### ISSUE THREAD

**Issue by panomza** [panomza/arduino#2]
ใน  library TM1637 Display มี delay อยู่ทำให้ Function Dim มีปัญหาไฟกระพริบ

**Comment by thanakijwanavit** [comment]
You should check out this article about pwm for atmega 328p
https://sites.google.com/site/qeewiki/books/avr-guide/pwm-on-the-atmega328

**Comment by thanakijwanavit** [comment]
Done
